version: "3.3"
services:
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - 15432:5432
networks:
  dev:
volumes:
  db: