version: "3.7"
services:
  dev_db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 15432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev
networks:
  dev:
volumes:
  db: